// <auto-generated />
namespace XmsExamToDo.Migrations.LibraryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addlibrarymigrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlibrarymigrations));
        
        string IMigrationMetadata.Id
        {
            get { return "201808171112187_add library migrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
